name: goth_mood_tracker
description: A dead simple, gloriously bleak mood tracker.
publish_to: "none"
version: 0.1.6+15

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  shared_preferences: ^2.2.3
  share_plus: ^10.0.2
  screenshot: ^2.5.0
  path_provider: ^2.1.4
  instagram_share_plus: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

