name: goth_mood_tracker
description: A dead simple, gloriously bleak mood tracker.
publish_to: "none"
version: 0.1.6+15

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^6.0.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

